routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/profile',function(){ return view('pages.profile');});
// Route::get('/notifications',function(){ return view('pages.notifications');});
// Route::get('/login',function(){ return view('pages.login');});
// Route::get('/publish',function(){ return view('pages.posts');});
// Route::get('/brows',function(){ return view('pages.brows');});
// // Route::get('/upload',function(){ return view('pages.upload');});

// Route::post('/insertpage','postController@getPosts');
// Route::post('/insertcomment','postController@getcomments');
// Route::get('/about','taskController@show');
// Route::get('/colorpage','taskController@getColorData');
// Route::get('/tagpage','taskController@getTagData');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',function(){ return view('welcome');});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function()
	{
		Route::post('projects/adduser', 'ProjectsController@adduser')->name('project.adduser');
		Route::get('projects/create/{company_id?}', 'ProjectsController@create');
		Route::resource('companies','CompaniesController');
		Route::resource('projects','ProjectsController');
		Route::resource('roles','RolesController');
		Route::resource('tasks','TasksController');
		Route::resource('users','UsersController');
		Route::resource('comments','CommentsController');
	});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right glyphicon glyphicon-user " >
                        <!-- Authentication Links -->
                        @guest
                        <li><a href="{{ route('login') }}" > <i class="fa fa-sigin-in"></i> Login</a></li>
                        <li><a href="{{ route('register') }}"> <i class="fa fa-user-plus"></i> Register</a></li>
                        @else
                         <li><a href="{{ route('companies.index') }}"> <i class="fa fa-building"></i> my compaines</a></li>
                        <li><a href="{{ route('projects.index') }}"> <i class="fa fa-briefcase"></i> Projects</a></li>
                         <li><a href="{{ route('tasks.index') }}"> <i class="fa fa-tasks"></i> Tasks</a></li>
                        @if(Auth::user()->role_id ==1)
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
								   <i class="fa fa-user"></i> Admin <span class="caret"></span>
								</a>

								<ul class="dropdown-menu">
									<li><a href="{{ route('companies.index') }}"> <i class="fa fa-building"></i> All compaines</a></li>
									<li><a href="{{ route('projects.index') }}"> <i class="fa fa-briefcase"></i> All Projects</a></li>
									<li><a href="{{ route('tasks.index') }}"> <i class="fa fa-tasks"></i> All Tasks</a></li>
									<li><a href="{{ route('users.index') }}"> <i class="fa fa-user"></i> All Users</a></li>
									<li><a href="{{ route('roles.index') }}">  <i class="fa fa-envelope"></i> All Roles</a></li>
								</ul>
							</li>
						@endif
						<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                               <i class="fa fa-user"></i> {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    <i class="fa fa-power-off"></i> Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
	
          @include('partials.errors')
          @include('partials.success')
        <div class="row">
            
            @yield('content')
        </div>
        
    </div>
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>

<script src="{{ asset('js/fontawesom.js') }}"></script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link rel="shortcut icon" href="img/eye.ico">
	@yield ('title')
	<link rel="stylesheet" href="">
</head>
<body>

	<h1>@yield ('title')</h1>		
	
	<div>
		@yield ('content')
	</div>
	
</body>
</html>