routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/profile',function(){ return view('pages.profile');});
// Route::get('/notifications',function(){ return view('pages.notifications');});
// Route::get('/login',function(){ return view('pages.login');});
// Route::get('/publish',function(){ return view('pages.posts');});
// Route::get('/brows',function(){ return view('pages.brows');});
// // Route::get('/upload',function(){ return view('pages.upload');});

// Route::post('/insertpage','postController@getPosts');
// Route::post('/insertcomment','postController@getcomments');
// Route::get('/about','taskController@show');
// Route::get('/colorpage','taskController@getColorData');
// Route::get('/tagpage','taskController@getTagData');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',function(){ return view('welcome');});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function()
	{
		Route::post('projects/adduser', 'ProjectsController@adduser')->name('project.adduser');
		Route::get('projects/create/{company_id?}', 'ProjectsController@create');
		Route::resource('companies','CompaniesController');
		Route::resource('projects','ProjectsController');
		Route::resource('roles','RolesController');
		Route::resource('tasks','TasksController');
		Route::resource('users','UsersController');
		Route::resource('comments','CommentsController');
	});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
     protected $fillable = [
        'name', 'description','days','user_id','company_id',
    ];
    public function users()
    {
        return $this->belongsToMany('App\User');
    }

public function companies()
    {
        return $this->belongsTo('App\Company');
    }
     public function tasks()
    {
        return $this->hasMany('App\Task');
    }
	
	public function comments()
    {
        return $this->morphMany('App\Comment','commentable');
    }

}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\User;
use App\Project;
use App\ProjectUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::check()){

        $projects=Project::where('user_id',Auth::user()->id)->get();
        return view('projects.index',['projects'=>$projects]) ;
        }
        return view('auth.login');
    }
	
	
	 /**
     * Show the form for Add new User.
     *
     *
     */
	public function adduser(request $request)
		{
			$project= Project::find($request->input('project_id'));
			
			//check if the person that add  in the project 
			if(Auth::user()->id == $project->user_id){
				$user=User::where('email',$request->input('email'))->first();
				
				$project_user=ProjectUser::where('project_id',$project->id)->first();
				//$projectuser=ProjectUser::where('user_id',$user->id)->where('project_id',$project->id)->first();
			
			//check if the email already exist
				if($project_user)
				{
					  return redirect()->route('projects.show',['project'=>$project->id])->with('success',$request->input('email').'already existin the project');
				}
				

				//check if i get the id of the user and the project and add attach the comment to the project 
				if($user && $project){
					$project->users()->attach($user->id);
					 return redirect()->route('projects.show',['project'=>$project->id])->with('success',$request->input('email').'Added to Project successfully');
				}
			}
			return back()->withInput()->with('errors',$request->input('email').' error Added to Project ');
		}
		
		
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create( $company_id=null )
    {
        //
		$companies=null;
	if(!$company_id)
	{
		$companies=Company::where('user_id',Auth::user()->id)->get();
	}
     return view('projects.create',['company_id' => $company_id ,'companies'=>$companies]);

 }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(Auth::check()){
         $project=Project::create([
            'name'=>$request->input('projectName'),
            'description'=>$request->input('projectDescription'),
			'company_id'=>$request->input('company_id'),
			
            'user_id'=>Auth::user()->id
            ]);
         if($project){ 
            return redirect()->route('projects.show',['project'=>$project->id])->with('success','project created successfully');
        }
    }
    return back()->withInput()->with('errors','project could not be created ');
}

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
        // $project=Project::where('id',$project->id)->first();
     $project=Project::find($project->id);
	 $comments=$project->comments;
     return view('projects.show',['project'=>$project,'comments'=>$comments]);
 }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
     $project=Project::find($project->id);
     return view('projects.edit',['project'=>$project]);
 }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
         // $project=Project::find($project->id);
         // $project->name=$request->projectName;
         // $project->description=$request->projectDescription;
         // $project->save();
        // return view('projects.show',['project'=>$project]);
        $findProject=Project::find($project->id);
        $projectUpdate=$findProject->update([
            'name'=>$request->input('projectName'),
            'description'=>$request->input('projectDescription')
            ]);
        if($projectUpdate){ 
            return redirect()->route('projects.show',['project'=>$project->id])->with('success','project update successfully');
        }
        return back()->withInput()->with('errors','project could not be updated ');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
        // dd($project);
        $findProject=Project::find($project->id);
        if($findProject->delete()){ 
            return redirect()->route('projects.index')->with('success','project deleted successfully');
        }
        return back()->withInput()->with('errors','project could not be deleted ');
    }
}

resources/views/projects/create.blade.php
@include('app');

      <!-- The justified navigation menu is meant for single line per list item.
      Multiple lines will require custom code not provided by Bootstrap. -->
      

      <!-- Jumbotron -->
     <div class="col-md-8 col-lg-8 col-sm-9 pull-left" style=" background=:white" >
	  <h1> Create project</h1>

      	<!-- Example row of columns -->
      	<div class="row " class="col-md-12 col-lg-12 col-sm-12 " style="background:white; margin: 10px">
      		<form action="{{route('projects.store')}}" method="post" accept-charset="utf-8">
      			{{csrf_field ()}}
      			
      			<div class="form-group">
      				<label for="project-name">name<span class="required">*</span></label>
      				<input type="text" class="form-control" id="project-name" required name="projectName" placeholder="Enter name">
      				
      			</div>
				<input type="hidden" name="company_id" value="{{$company_id}}"/>
				
				@if($companies != null)
					<div class="form-group ">
						<label for="project-name">select your company</label>
						<select name="company_id"  class="form-control">
							@foreach($companies as $company)
								<option value="{{$company->id}}">{{$company->name}}</option>
							@endforeach
						</select>
					</div>
				@endif
					
		
      			<div class="form-group">
      				<label for="project-description">description<span class="required">*</span></label>
      				<textarea  class="form-control" id="project-description" required rows="4" name="projectDescription" placeholder="Enter description" style="resize: vertical;" ></textarea>
      			</div>
      			<button type="submit" class="btn btn-primary">Submit</button>
      		</form>

      	</div>
      </div>


      <div class="col-sm-3 col-md-3 col-lg-3  pull-right">
      	<div class="sidebar-module">
      		<h4>Actions</h4>
      		<ol class="list-unstyled">
      		<li><a href="/projects">myprojects</a></li>
      			<!-- <li><a href="">Delete</a></li>
      			<li><a href="#">AddNewMmeber</a></li> -->
      		</ol>
      	</div>
      	<div class="sidebar-module">
      		<h4>Members</h4>
      		<ol class="list-unstyled">
      			<li><a href="#">March 2014</a></li>

      		</ol>
      	</div> 

      </div>


  </div>

resources/views/projects/edit.blade.php
@include('app');

      <!-- The justified navigation menu is meant for single line per list item.
      Multiple lines will require custom code not provided by Bootstrap. -->
      

      <!-- Jumbotron -->
      <div class="col-md-8 col-lg-8 col-sm-9 pull-left" style=" background=:white" >
	  <h1> Update project</h1>

      	<!-- Example row of columns -->
      	<div class="row " class="col-md-12 col-lg-12 col-sm-12 " style="background:white; margin: 10px">
      		<form action="{{route('projects.update',[$project->id])}}" method="post" accept-charset="utf-8">
      			{{csrf_field()}}
      			<input type="hidden" name="_method" value="put">
      			<div class="form-group">
      				<label for="project-name">name<span class="required">*</span></label>
      				<input type="text" class="form-control" id="project-name" required name="projectName" placeholder="Enter name" value="{{$project->name}}">
      				
      			</div>
      			<div class="form-group">
      				<label for="project-description">description<span class="required">*</span></label>
      				<textarea  class="form-control" id="project-description" required rows="4" name="projectDescription" placeholder="Enter description" style="resize: vertical;" >{{$project->description}}</textarea>
      			</div>
      			<button type="submit" class="btn btn-primary">Submit</button>
      		</form>

      	</div>
      </div>


      <div class="col-sm-3 col-md-3 col-lg-3  pull-right">
      	<div class="sidebar-module">
      		<h4>Actions</h4>
      		<ol class="list-unstyled">
      		<li><a href="/projects">Viewprojects</a></li>
      			<!-- <li><a href="">Delete</a></li>
      			<li><a href="#">AddNewMmeber</a></li> -->
      		</ol>
      	</div>
      	<div class="sidebar-module">
      		<h4>Members</h4>
      		<ol class="list-unstyled">
      			<li><a href="#">March 2014</a></li>

      		</ol>
      	</div> 

      </div>


  </div>

resources/views/projects/index.blade.php
@include('app');

<div class=" col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
	
	<div class="panel panel-primary ">
		<div class="panel-heading">
				projectS
				<a href="/projects/create" class="btn btn-primary  btn-sm pull-right" >Create New</a>
		</div>
		<div class="panel-body">
			<ul class="list-group">
				@foreach($projects as $project)
				<li class="list-group-item">
					<a href="/projects/{{$project->id}}"> {{$project->name}}</a>
				</li>
				@endforeach

			</ul>
		</div>
	</div>
</div>

resources/views/projects/show.blade.php
@include('app');

      <!-- The justified navigation menu is meant for single line per list item.
      Multiple lines will require custom code not provided by Bootstrap. -->
      

      <!-- Jumbotron -->
      <div class="col-md-8 col-lg-8 col-sm-9 pull-left">
      	<div class="well well-lg">
			
      		<h1>{{$project->name}}</h1>
      		<p class="lead">{{$project->description}}</p>
      	</div>

      	<!-- Example row of columns -->
		<div class="row containar-fluid col-md-12 col-lg-12 col-sm-12 " style="background:white; margin: 10px">
		@include('partials.comments')
		<br/>
		
      		<form action="{{route('comments.store')}}" method="post" accept-charset="utf-8">
      			{{csrf_field()}}
      			
				<input type="hidden" name="commentable_id" value="{{$project->id}}">
				<input type="hidden" name="commentable_type" value="App\Project">
      			<div class="form-group">
      				<label for="comment-content">enter your comment</label>
      				<textarea  class="form-control autosize-target text-left" id="comment-content" required rows="3" name="commentBody" placeholder="Enter your comment" style="resize: vertical;" ></textarea>
      			</div>
				<div class="form-group">
      				<label for="comment-content">proof your comment(url/screen Shots)</label>
      				<textarea  class="form-control autosize-target text-left" id="comment-content" required rows="2" name="commentUrl" placeholder="Enter your (url/screen Shots)" style="resize: vertical;" ></textarea>
      			</div>
      			
      			<button type="submit" class="btn btn-primary">Submit</button>
      		</form>

      	</div>
				
			
	     </div>


      <div class="col-sm-3 col-md-3 col-lg-3  pull-right">
      	<div class="sidebar-module">
      		<h4>Actions</h4>
      		<ol class="list-unstyled">
      			<li><a href="/projects/{{$project->id}}/edit"> <i class="fa fa-edit"></i> Edite</a></li>
      			
      			<li><a href="/projects">Viewprojects</a></li>
      			<br/>
				@if ( $project->user_id == Auth::user()->id)
      			<li>
      				<a href="#" onclick="
      				var result= confirm('ARE yOU Sure You Wish TO delete this project?');
      				if(result)
      				{
      					event.preventDefault();
      					document.getElementById('delete-form').submit();
      				}
      				">
      				Delete</a>
      				<form  id="delete-form" action="{{route('projects.destroy',[$project->id])}}" 
      					method="post" accept-charset="utf-8">
      					<input type="hidden" name="_method" value="delete">
      					{{csrf_field()}}

      				</form>
      			</li>
				@endif
      		</ol>
			<br/>
			
			<h4>Add_Members</h4>
			<div class="row">
				<div class="col-md-12 col-lg-12 col-sm-12">
				
				<form  id="add-user" action="{{route('project.adduser')}}" method="post" accept-charset="utf-8">
						{{csrf_field()}}
					<div class="input-group">
					<input type="hidden" name="project_id" value="{{$project->id}}">
						<input type="text" class="form-control" name="email" placeholder="Emial">
						<span class="input-group-btn">
							<button class="btn btn-primary" type="submit">Add!</button>
						</span>
					</div><!-- /input-group -->
				</form> 
			
				</div><!-- /.col-lg-6 -->
			</div><!-- /.row -->
      	</div> 
		
		<br/>
			<div class="sidebar-module">
      		<h4>Members</h4>
			<ol class="list-unstyled">
			@foreach($project->users as $user) 
      			<li><a href="#"> Email:{{$user->email}} ({{$user->name}})</a></li>
			@endforeach

      		</ol>
      		
      	</div> 
      
      	<!-- <div class="sidebar-module sidebar-module-inset">
      		<h4>About</h4>
      		<p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      	</div>-->
      </div>
      

  </div>