routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/profile',function(){ return view('pages.profile');});
// Route::get('/notifications',function(){ return view('pages.notifications');});
// Route::get('/login',function(){ return view('pages.login');});
// Route::get('/publish',function(){ return view('pages.posts');});
// Route::get('/brows',function(){ return view('pages.brows');});
// // Route::get('/upload',function(){ return view('pages.upload');});

// Route::post('/insertpage','postController@getPosts');
// Route::post('/insertcomment','postController@getcomments');
// Route::get('/about','taskController@show');
// Route::get('/colorpage','taskController@getColorData');
// Route::get('/tagpage','taskController@getTagData');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',function(){ return view('welcome');});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function()
	{
		Route::post('projects/adduser', 'ProjectsController@adduser')->name('project.adduser');
		Route::get('projects/create/{company_id?}', 'ProjectsController@create');
		Route::resource('companies','CompaniesController');
		Route::resource('projects','ProjectsController');
		Route::resource('roles','RolesController');
		Route::resource('tasks','TasksController');
		Route::resource('users','UsersController');
		Route::resource('comments','CommentsController');
	});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
     protected $fillable = [
        'name', 'description','user_id',
    ];
    public function users()
    {
        return $this->belongsTo('App\User');
    }
    public function projects()
    {
        return $this->hasMany('App\Project');
    }
	public function comments()
    {
        return $this->morphTo('App\Comment','commentable');
    }
    //  public function tasks()
    // {
    //     return $this->hasMany('App\Task');
    // }

}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::check()){

        $companies=Company::where('user_id',Auth::user()->id)->get();
        return view('companies.index',compact('companies')) ;
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
     return view('companies.create') ;

 }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(Auth::check()){
         $company=Company::create([
            'name'=>$request->input('companyName'),
            'description'=>$request->input('companyDescription'),
            'user_id'=>Auth::user()->id
            ]);
         if($company){ 
            return redirect()->route('companies.show',['company'=>$company->id])->with('success','company created successfully');
        }
    }
    return back()->withInput()->with('errors','company could not be created ');
}

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
        // $company=Company::where('id',$company->id)->first();
     $company=Company::find($company->id);
     return view('companies.show',['company'=>$company]);
 }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //
     $company=Company::find($company->id);
     return view('companies.edit',['company'=>$company]);
 }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        //
         // $company=Company::find($company->id);
         // $company->name=$request->companyName;
         // $company->description=$request->companyDescription;
         // $company->save();
        // return view('companies.show',['company'=>$company]);
        $findCompany=Company::find($company->id);
        $companyUpdate=$findCompany->update([
            'name'=>$request->input('companyName'),
            'description'=>$request->input('companyDescription')
            ]);
        if($companyUpdate){ 
            return redirect()->route('companies.show',['company'=>$company->id])->with('success','company update successfully');
        }
        return back()->withInput()->with('errors','company could not be updated ');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        //
        // dd($company);
        $findCompany=Company::find($company->id);
        if($findCompany->delete()){ 
            return redirect()->route('companies.index')->with('success','company deleted successfully');
        }
        return back()->withInput()->with('errors','company could not be deleted ');
    }
}

resources/views/companies/create.blade.php
@include('app');

      <!-- The justified navigation menu is meant for single line per list item.
      Multiple lines will require custom code not provided by Bootstrap. -->
      

      <!-- Jumbotron -->
      <div class="col-md-8 col-lg-8 col-sm-9 pull-left" style=" background=:white" >
	  <h1> creta Company</h1>

      	<!-- Example row of columns -->
      	<div class="row " class="col-md-12 col-lg-12 col-sm-12 " style="background:white; margin: 10px">
      		<form action="{{route('companies.store')}}" method="post" accept-charset="utf-8">
      			{{csrf_field()}}
      			
      			<div class="form-group">
      				<label for="company-name">name<span class="required">*</span></label>
      				<input type="text" class="form-control" id="company-name" required name="companyName" placeholder="Enter name">
      				
      			</div>
      			<div class="form-group">
      				<label for="company-description">description<span class="required">*</span></label>
      				<textarea  class="form-control" id="company-description" required rows="4" name="companyDescription" placeholder="Enter description" style="resize: vertical;" ></textarea>
      			</div>
      			<button type="submit" class="btn btn-primary">Submit</button>
      		</form>

      	</div>
      </div>


      <div class="col-sm-3 col-md-3 col-lg-3  pull-right">
      	<div class="sidebar-module">
      		<h4>Actions</h4>
      		<ol class="list-unstyled">
      		<li><a href="/companies">myCompanies</a></li>
      			<!-- <li><a href="">Delete</a></li>
      			<li><a href="#">AddNewMmeber</a></li> -->
      		</ol>
      	</div>
      	<div class="sidebar-module">
      		<h4>Members</h4>
      		<ol class="list-unstyled">
      			<li><a href="#">March 2014</a></li>

      		</ol>
      	</div> 

      </div>


  </div>

resources/views/companies/edit.blade.php
@include('app');

      <!-- The justified navigation menu is meant for single line per list item.
      Multiple lines will require custom code not provided by Bootstrap. -->
      

      <!-- Jumbotron -->
      <div class="col-md-8 col-lg-8 col-sm-9 pull-left" style=" background=:white" >
	  <h1> Update Company</h1>


      	<!-- Example row of columns -->
      	<div class="row " class="col-md-12 col-lg-12 col-sm-12 " style="background:white; margin: 10px">
      		<form action="{{route('companies.update',[$company->id])}}" method="post" accept-charset="utf-8">
      			{{csrf_field()}}
      			<input type="hidden" name="_method" value="put">
      			<div class="form-group">
      				<label for="company-name">name<span class="required">*</span></label>
      				<input type="text" class="form-control" id="company-name" required name="companyName" placeholder="Enter name" value="{{$company->name}}">
      				
      			</div>
      			<div class="form-group">
      				<label for="company-description">description<span class="required">*</span></label>
      				<textarea  class="form-control" id="company-description" required rows="4" name="companyDescription" placeholder="Enter description" style="resize: vertical;" >{{$company->description}}</textarea>
      			</div>
      			<button type="submit" class="btn btn-primary">Submit</button>
      		</form>

      	</div>
      </div>


      <div class="col-sm-3 col-md-3 col-lg-3  pull-right">
      	<div class="sidebar-module">
      		<h4>Actions</h4>
      		<ol class="list-unstyled">
      		<li><a href="/companies">ViewCompanies</a></li>
      			<!-- <li><a href="">Delete</a></li>
      			<li><a href="#">AddNewMmeber</a></li> -->
      		</ol>
      	</div>
      	<div class="sidebar-module">
      		<h4>Members</h4>
      		<ol class="list-unstyled">
      			<li><a href="#">March 2014</a></li>

      		</ol>
      	</div> 

      </div>


  </div>

resources/views/companies/index.blade.php
@include('app');

<div class=" col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
	
	<div class="panel panel-primary ">
		<div class="panel-heading">
				COMpANYS
				<a href="/companies/create" class="btn btn-primary  btn-sm pull-right" >Create New</a>
		</div>
		<div class="panel-body">
			<ul class="list-group">
				@foreach($companies as $company)
				<li class="list-group-item">
					<a href="/companies/{{$company->id}}"> {{$company->name}}</a>
				</li>
				@endforeach

			</ul>
		</div>
	</div>
</div>

resources/views/companies/show.blade.php
@include('app');

      <!-- The justified navigation menu is meant for single line per list item.
      Multiple lines will require custom code not provided by Bootstrap. -->
      

      <!-- Jumbotron -->
      <div class="col-md-8 col-lg-8 col-sm-9 pull-left">
      	<div class="jumbotron">
      		<h1>{{$company->name}}</h1>
      		<p class="lead">{{$company->description}}</p>
      	</div>

      	<!-- Example row of columns -->
      	<div class="row " style="background:white; margin: 10px">
		<a href="/projects/create/{{ $company->id }}" class="pull-right btn btn-defualt btn-sm">AddProject</a>
      		@foreach($company->projects as $project)
      		<div class="col-lg-4 col-md-4 col-sm-4">
      			<h2>{{$project->name}}</h2>
      			<p class="text-danger">{{$project->description}}</p>
      			<p>
      				<a class="btn btn-primary" href="/projects/{{$project->id}}" role="button">View project »</a>
      			</p>
      		</div>
      		@endforeach
      	</div>
      </div>


      <div class="col-sm-3 col-md-3 col-lg-3  pull-right">
      	<div class="sidebar-module">
      		<h4>Actions</h4>
      		<ol class="list-unstyled">
      			<li><a href="/companies/{{$company->id}}/edit"> <i class="fa fa-edit"></i> Edite</a></li>
      			<li><a href="/companies">ViewCompanies</a></li>
      			<li><a href="/companies/create">AddNewcompanies</a></li>
      			<li><a href="/projects/create/{{ $company->id }}">AddNewProject</a></li>
      			<br/>
      			<li>
      				<a href="#" onclick="
      				var result= confirm('ARE yOU Sure You Wish TO delete this project?');
      				if(result)
      				{
      					event.preventDefault();
      					document.getElementById('delete-form').submit();
      				}
      				">
      				Delete</a>
      				<form  id="delete-form" action="{{route('companies.destroy',[$company->id])}}" 
      					method="post" accept-charset="utf-8">
      					<input type="hidden" name="_method" value="delete">
      					{{csrf_field()}}

      				</form>
      			</li>
      		</ol>
      	</div>
      	<div class="sidebar-module">
      		<h4>Members</h4>
      		<ol class="list-unstyled">
      			<li><a href="#">March 2014</a></li>

      		</ol>
      	</div> 
      	<!-- <div class="sidebar-module sidebar-module-inset">
      		<h4>About</h4>
      		<p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      	</div>-->
      </div>
      

  </div>